name: erx
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  velocity_x: ^4.2.1
  cloud_firestore: ^6.1.0
  double_back_to_close_app: ^2.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter_svg: ^2.2.3
  fluttertoast: ^9.0.0
  google_fonts: ^6.3.3
  intl: ^0.20.2
  lottie: ^3.3.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  get: ^4.6.5  # âœ… GetX included
  firebase_storage: ^13.0.4
  image_picker:  ^0.8.7+5

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/logo/

flutter_icons:
  android: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "assets/logo/background.png"
  adaptive_icon_foreground: "assets/logo/foreground.png"
